name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # inputs:
    #   METHOD:
    #     description: 'Method to use'
    #     required: true
    #     default: 'find-and-replace'
    #     type: choice
    #     options:
    #       - find-and-replace
    #       - shell

permissions:
  # Required to be able to update and commit the README.md file.
  contents: write

jobs:
  find-and-replace:
    name: Find and Replace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: <-- FR-Generated -->([\s\S]*?)<-- !FR-Generated -->
          include: README.md
          replace: |
            <-- FR-Generated -->

            - **Last Commit Message**: ${{ github.event.head_commit.message }}

            - **Last Commit Author**: ${{ github.event.head_commit.author.name }}

            - **Last Commit Date**: ${{ github.event.head_commit.timestamp }}

            <-- !FR-Generated -->

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4

  shell:
    name: Bash Method
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace
        run: |
          sed -i "s/<-- SH-Generated -->[\s\S]*?<-- !SH-Generated -->/${{ github.event.head_commit.message }}/g" README.md

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
