name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      METHOD:
        description: 'Method to use'
        required: true
        default: 'find-and-replace'
        type: choice
        options:
          - find-and-replace
          - shell

permissions:
  # Required to be able to update and commit the README.md file.
  contents: write

env:
  REPLACE_OPEN: '<-- Generated -->'
  REPLACE_CLOSE: '<-- !Generated -->'

jobs:
  find-and-replace:
    name: Find and Replace
    runs-on: ubuntu-latest
    # Run if inputs.METHOD == 'find-and-replace' or is null.
    if: ${{ inputs.METHOD == 'find-and-replace' || inputs.METHOD == null }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: ${{ env.REPLACE_OPEN }}([\s\S]*?)${{ env.REPLACE_CLOSE }}
          include: README.md
          replace: "${{ env.REPLACE_OPEN }}\n Last Commit Message: ${{ github.event.head_commit.message }}\n Last Commit Author: ${{ github.event.head_commit.author.name }}\n Last Commit Date: ${{ github.event.head_commit.timestamp }}\n${{ env.REPLACE_CLOSE }}"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4

  shell:
    name: Bash Method
    runs-on: ubuntu-latest
    if: ${{ inputs.METHOD == 'shell' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Replace
        run: |
          sed -i "s/${{ env.REPLACE_OPEN }}[\s\S]*?${{ env.REPLACE_CLOSE }}/${{ github.event.head_commit.message }}/g" README.md

      - name: Commit and Push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add README.md
          git commit -m "Updated README.md"
          git push
