name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  # Required to be able to update and commit the README.md file.
  contents: write

env:
  REPLACE_BODY: |
    - **Last Commit Message**: ${{ github.event.head_commit.message }}

    - **Last Commit Author**: ${{ github.event.head_commit.author.name }}

    - **Last Commit Date**: ${{ github.event.head_commit.timestamp }}

jobs:
  find-and-replace:
    name: Find and Replace
    runs-on: ubuntu-latest
    env:
      REPLACE_OPEN: '{#GENERATED#}'
      REPLACE_CLOSE: '{!GENERATED!}'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: ${{env.REPLACE_OPEN}}([\s\S]*?)${{env.REPLACE_CLOSE}}
          include: README.md
          replace: |
            ${{ env.REPLACE_OPEN}}

            ${{ env.REPLACE_BODY }}

            ${{ env.REPLACE_CLOSE }}

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
